/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Matriz;
import java.util.*;
import javax.swing.JOptionPane;

public class App {
    public String getGreeting() {
        return "intro para continuar";
    }

    public static void main(String[] args) {

        Matrices matriz = new Matrices();
         
        System.out.println(matriz.MyMatrix());
        matriz.MagicCubeI();
        System.out.println(matriz.TicTacToe());
        
    }
    
   
}
